In [1]:
import numpy as np

In [4]:
## номер 1
def result_mark(weights: np.array, marks: np.array) -> np.array:
    weights = np.array(weights).reshape(1, -1)
    finalMarkContrElem = weights * marks
    finaMarkcourse = np.round(np.sum(finalMarkContrElem, axis = 1)).astype(int)
    return finaMarkcourse


# weights = np.array([0.3, 0.4, 0.2, 0.1])
# marks = np.array([[7, 10, 8, 6], [6, 9, 7, 6]])
# assert np.allclose(result_mark(weights, marks), np.array([8, 7]))
# weights = np.array([0.3, 0.4, 0.2, 0.1])
# marks = np.array([[4, 0, 7, 8] , [5, 7, 1, 3]])
# result = result_mark(weights, marks)
# result

In [5]:
## номер 2
def change_array(array: np.array) -> np.array:
    result = np.where(array % 2 == 0, array ** 2, np.sin(array))
    result = np.round(result, 2)
    return result

# array = np.array([2, 5, 1, 0, -6, 22, 213431])
# assert np.allclose(change_array(array), np.array([4.0, -0.96, 0.84, 0.0, 36.0, 484.0, -0.58]))
# array = np.array([3, 12, 15, -97, 6])
# result = change_array(array)
# result

In [6]:
## номер 3
def cumulative_sum_of_differences(array):
    array[1:] -= array[:-1]
    array[0] = 0
    cum_sum = np.cumsum(array)
    return cum_sum

# array = np.array([3, 6, 2, 8])
# assert np.allclose(cumulative_sum_of_differences(array), np.array([0, 3, -1, 5]))
# array = np.array([0, 0, 0, 0])
# array = cumulative_sum_of_differences(array)
# array

In [7]:
## номер 4
def flatten_and_sort_transposed(array: np.array) -> np.array:
    transpose_array = array.T
    reshape_array = transpose_array.reshape(-1)
    array = reshape_array.astype(np.int8)
    array = np.sort(array)[::-1]
    return array

# array = np.array([[256, -10], [-381, 112]])
# assert np.allclose(flatten_and_sort_transposed(array), np.array([112, 0, -10, -125]))
# array = np.array([[9, 8, 7], [3, 6, 129]])
# array = flatten_and_sort_transposed(array)
# array

In [9]:
## номер 5
def filter_rows_by_mean(array):
    mean = np.mean(array)
    mean_row =np.mean(array, axis = 1)
    lines_remove = np.where(mean_row > mean)[0]
    array = np.delete(array, lines_remove, axis=0)
    return array

# array = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
# res = filter_rows_by_mean(array)
# assert res.ndim == 2
# assert np.allclose(res, np.array([[1, 2, 3], [4, 5, 6]]))
# array = np.array([[10, 20], [5, 5], [15, 15]])
# res = filter_rows_by_mean(array)
# res

In [10]:
## номер 6 (1 способ)
def create_checkerboard(number):
    matrix = np.fromfunction(lambda i, j: ((i + j + 1) % 2), (number, number), dtype = int)
    return matrix

# number = 3
# assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))
# number = 4
# res = create_checkerboard(number)
# res

In [18]:
## 6 номер (2 способ)
def create_checkerboard(number):
    i = np.arange(number)
    j = np.arange(number)
    i, j = np.meshgrid(i, j)
    matrix = (i + j + 1) % 2
    return matrix


# number = 3
# assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))
# number = 5
# res = create_checkerboard(number)
# res

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [22]:
## 6 номер (3 способ)
def create_checkerboard(number):
    matrix = (np.indices((number, number)).sum(axis=0)+1) % 2
    return matrix

# number = 3
# assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))
# number = 5
# res = create_checkerboard(number)
# res

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [11]:
## номер 7
def sort_rows_by_second_column(array):
    sort = np.argsort(array[:, 1])
    array = array[sort]
    return array

# array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0], [6, -1, 5]])
# assert np.allclose(sort_rows_by_second_column(array), np.array([[6, -1, 5], [10, 3, 9], [2, 7, 0], [5, 8, 1]]))
# array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0], [6, -1, 5]])
# array = sort_rows_by_second_column(array)
# array

In [12]:
## номер 8
def sum_counterdiagonal_elements(array):
    array_transpose = array.T[::-1]
    diagonal = np.diag(array_transpose)
    summa = np.sum(diagonal)
    return summa

# array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0]])
# assert sum_counterdiagonal_elements(array) == 6
# array = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
# summa = sum_counterdiagonal_elements(array)
# summa

In [13]:
## номер 9
def generate_logarithm_points(start, end, count):
    points = np.round(np.linspace(start, end, count),2)
    point_log = np.round(np.log(points + 1), 2)
    result = np.column_stack((points, point_log))
    return result


# start = 1
# end = 10
# count = 5
# assert np.allclose(generate_logarithm_points(start, end, count), np.array([[1., 0.69], [3.25, 1.45], [5.5 , 1.87], [7.75, 2.17], [10., 2.4]]))
# start = 5
# end = 12
# count = 4
# array = generate_logarithm_points(start, end, count)
# array

In [14]:
## номер 10
def min_max_scale(array):
    normalization = np.where(np.max(array) != np.min(array), (array - np.min(array))/(np.max(array)-np.min(array)), np.zeros_like(array))
    normalization = np.round(normalization, 2)
    return normalization    

# array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# array1 = np.array([[5, 5, 6], [5, 5, 5]])
# print(min_max_scale(array1))
# assert np.allclose(min_max_scale(array), np.array([[0. , 0.12, 0.25], [0.38, 0.5 , 0.62], [0.75, 0.88, 1.]]))
# array = np.array([[2, 2, 2], [2, 2, 2]])
# array = min_max_scale(array)
# array

[[0. 0. 1.]
 [0. 0. 0.]]
